language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
# install dependencies
services:
    - postgresql
addons:
    postgresql: "9.4"
before_script:
    - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
    - psql -c "CREATE ROLE travis_ci_test WITH SUPERUSER LOGIN PASSWORD 'travis_ci_password';" -U postgres
    - psql -f tests/fixtures.sql -d $DB_NAME
    - pip install -U setuptools
script: "python setup.py test"
